.TH CANTERA-TABLE 1 "Feb 2013"
.PP
.SH "NAME"
ca-shell \- the Cantera Table shell
.SH "GETTING HELP"
.PP
The following manual pages have been written to document the operation of this software:
.TP
\fBca-shell\fR
This manual page
.TP
\fBca-sql\fR
Query language description
.SH "DESCRIPTION"
.PP
Provides an interactive shell in which to query Cantera Table databases using an SQL-like syntax.
.TP
\fB--c, --command=\fRSTRING
Execute the commands in \fBSTRING\fR and exit
.TP
\fB--help\fR
Display help text and exit
.TP
\fB--version\fR
Display version information and exit
.SH "AUTHOR"
.PP
This manual page was written by Morten Hustveit <morten.hustveit@gmail.com>.
